### ISSUE TITLE
Problemas con el despliegue en vercel o netlify

### ISSUE THREAD

**Issue by ClaudiaTC02** [ULL-MII-SYTWS-2425/intro2sd-claudia-torres-cruz-alu0101418285#17]
Hola, cuando accedo para hacer el despliegue en netlify me dice que no tengo permisos:

![netlify](https://github.com/user-attachments/assets/220e3600-a1a8-4863-acee-6a8cab78caa9)

 En Vercel me dice que mejore mi cuenta a pro para acceder a organizaciones:

![vercel](https://github.com/user-attachments/assets/45cea9a3-acfb-4230-b7b7-728e32910b73)

**Comment by crguezl** [comment]
@ClaudiaTC02  

Le haces un fork a tu cuenta y le pones visibilidad pública y despliegas desde ahí. Así no cobran

**Comment by ClaudiaTC02** [comment]
Ahhh vale gracias, no lo sabía
