### ISSUE TITLE
Terminé intro2sd

### ISSUE THREAD

**Issue by ClaudiaTC02** [ULL-MII-SYTWS-2425/intro2sd-claudia-torres-cruz-alu0101418285#20]

**Comment by crguezl** [comment]
@ClaudiaTC02 

Me ha encantado y eso que no me gusta el género de terror.
Algunos de los links de Las imágenes de la colección  de Halloween están fallando.

¡Buen trabajo!

**Comment by ClaudiaTC02** [comment]
Gracias! Fallando? Yo veo todas las imágenes bien, no hay ninguna rota. A que te refieres?

**Comment by crguezl** [comment]
Cierto!
 
Debió ser que falló la red o algo, porque ahora se ven perfecto!
